#summarise findings and show to Tim
#pdf('Summary.pdf')



#PART TWO SELF-INHIBITION AND ACTIVATION
#pdf('Self-Inhibition.pdf')

#This is to look at sensitivity to external signals of single and multiple genes 

#Inhibition 

k1<-1
k2<-1
r<-2
d<-1
N<-1:100

S1<-(-d*k2+sqrt(d*k2)*sqrt(d*k2+4*k1*N*r))/(2*k1*r)
S2<-N-S1
Pr<-(-d*k2+sqrt(d*k2)*sqrt(d*k2+4*k1*N*r))/(k1*2*d)
par(mfrow=c(1,1),mar=c(5,5,5,5))
plot(S1/N~N,type='l',col='black',lwd=3,main='Self Inhibition',ylab='% gene on')

plot(Pr~N,type='l',col='black',lwd=3,main='Self Inhibition',ylab='Products level')



#plot(Pr~N,type='l',col='red',lwd=3)

#legend('topright',legend = c('N=1','N=10'),col = c('Blue','Red'),lwd = 3)

#Stochastic version 

source('./InhibitionFunction.R')
NumberOfGene <-100
Target<-SelfInhiSimu(NumberOfGene =NumberOfGene)

par(mfrow=c(1,1),mar=c(5,5,5,5))
plot(Target$S1/NumberOfGene~Target$Time,type='S',col='red',lwd=2,ylab='% of gene on',xlab='Time',main='Self Inhibition',ylim=c(0,1))

NumberOfGene <-10
Target<-SelfInhiSimu(NumberOfGene =NumberOfGene)
lines(Target$S1/NumberOfGene~Target$Time,type='S',col='green',lwd=2)

NumberOfGene <-1
Target<-SelfInhiSimu(NumberOfGene =NumberOfGene)
lines(Target$S1/NumberOfGene~Target$Time,type='S',col='blue',lwd=2)

par(xpd=T)
legend('topright',legend = c('N=1','N=10','N=100'),col = c('Blue','green','Red'),lwd = 3,cex=1.3)


#PART 3 HETERO GENEIRY GENERATED BY SLEF-INHIBITION 

source(file = 'Gillespie.R')
set.seed(124)
NumberOfGene<-10
NumberOfState<-2

setwd("~/Box Sync/research/Third year 3/Gillespie/records/20160318")
#pdf('Simulation part 2.pdf')
x0<-c(rep(0,NumberOfGene*(NumberOfState-1)),rep(1,NumberOfGene),0)

GName<-paste('G',1:NumberOfGene,sep = '')
StName<-paste('S',1:NumberOfState,sep = '')
names(x0)<-c(as.vector(sapply(X = StName,FUN = function(x){paste(GName,x,sep='')})),'Pr')

Parm<-c(k12=1,k21=10,p=10,d=1)

a<-c(paste('(k12/(1+Pr))*',grep(StName[1],names(x0),value = T),sep=''),
     paste('k21*',grep(StName[2],names(x0),value = T),sep=''),
     paste('p*','sum(',paste(GName,StName[2],sep = '',collapse =','),')',sep =''),#I am not differentiating Pr from different copies
     'd*Pr')



nu<-matrix(data =0,nrow = length(x0),ncol = length(a),byrow = T )
colnames(nu)<-a
rownames(nu)<-names(x0)

for (i in 1:NumberOfGene){
        nu[c(i,i+NumberOfGene),i]<-c(-1,1)
        nu[c(i,i+NumberOfGene),i+NumberOfGene]<-c(1,-1)
}

nu['Pr',ncol(nu)-1]<-1
nu['Pr',ncol(nu)]<--1

Miega<-DianboGLP(x0,a,Parm,nu,FinalTime = 10,WallTime = 2)

#polish the graph for report 

ActiveCopies<-rowSums(Miega[,grep('S2',colnames(Miega),value = T)])
#plot(Miega[,'Time'],ActiveCopies,type = 's',xlab='Time',ylab='NO. of active copies')

##look at each copy

ColVec<-rainbow(n = NumberOfGene)
t(Miega)
par(mfrow=c(1,1),mar=c(5,5,5,5))
EvTime <- Miega[-1,1] - Miega[-nrow(Miega),1]
B<-barplot(t(Miega[,(NumberOfGene+2):(2*NumberOfGene+1)]),col=ColVec,width = EvTime,border = NA,xaxt='n',
           xlab = 'Time',ylab = 'NO. of active copies',names.arg = round(Miega[,1],2))
B
axis(side = 1,labels = c('0','2.5','5','7.5','10'),at = c(0,2.5,5,7.5,10),cex=2)

##now the question become how to demostrate situation in the popuplation. 

### one of the simplest thing to do is multiple stack bar chart
#barplot(cbind(Miega[,1],Miega2[,1]))

ColForGene<-rep('white',nrow(Miega))
####function to determine color

#install.packages('gplots')      
library(gplots)
WhichColor<-function(x){
        VecExp<-which(x==1)#which gene is active
        if (length(VecExp)>1){return(col2hex('black'))}
        if (length(VecExp)==1){return(ColVec[VecExp])}
        if (length(VecExp)<1){return(col2hex('white'))}
}


ColPro<-apply(Miega[,(NumberOfGene+2):(2*NumberOfGene+1)],1,FUN = WhichColor)
Miega<-cbind(Miega,ColPro)        


par(mfrow=c(11,1),mar=c(0,0,0,0))
for (i in 1:10){
        
        Miega2<-DianboGLP(x0,a,Parm,nu,FinalTime = 10,WallTime = 2)
        #dim(Miega2)
        ColPro<-apply(Miega2[,(NumberOfGene+2):(2*NumberOfGene+1)],1,FUN = WhichColor)
        Miega2<-cbind(Miega2,ColPro)   
        #head(Miega2)
        
        # barplot(cbind(as.numeric(Miega[,1]),as.numeric(Miega2[,1])),col = Miega[,ncol(Miega)])
        
        barplot(as.matrix(as.numeric(Miega2[,1])),col =Miega2[,ncol(Miega2)] ,horiz = T,xaxt='n',border = NA)
}

axis(side = 1,labels = c('0','2.5','5','7.5','10'),at = c(0,100,300,400,600),cex=2)
par(mfrow=c(1,1))


#dev.off()







#PART 4 EFFECTIVENSS IN LONG CHAIN 

#pdf('Longchian.pdf')
##4.1 LOOK AT A SINGLE CHAIN 


#This is to look at responsive curve of each node 
par(mfrow=c(1,1),mar=c(4,4,3,3))

SimuChains<-function(NOG,IM,LengthOfChain,k12,k21,r,d){
        NumberofGene<-NOG
        LengthOfChain<-LengthOfChain
        
        
        ParaMat<-matrix(data = 1,nrow = LengthOfChain,ncol = 4)
        colnames(ParaMat)<-c('k12','k21','r','d')
        ParaMat[,'k12']<-k12
        ParaMat[,'k21']<-k21
        ParaMat[,'r']<-r
        ParaMat[,'d']<-d
        
        IM<-IM
        
        EquiMat<-array(0,dim=c(LengthOfChain,3,length(IM)))
        colnames(EquiMat)<-c('S1','S2','Pr')
        
        for (j in 1:length(IM)){
                i<-1#first node 
                EquiMat[i,'S1',j]<-NumberofGene/((ParaMat[i,'k12']/ParaMat[i,'k21'])*IM[j]+1)
                EquiMat[i,'S2',j]<-NumberofGene-EquiMat[i,'S1',j]
                EquiMat[i,'Pr',j]<-(ParaMat[i,'r']/ParaMat[i,'d'])*EquiMat[i,'S1',j]
                
                for (i in 2:nrow(EquiMat)){
                        EquiMat[i,'S1',j]<-NumberofGene/((ParaMat[i,'k12']/ParaMat[i,'k21'])*EquiMat[i-1,'Pr',j]+1)
                        EquiMat[i,'S2',j]<-NumberofGene-EquiMat[i,'S1',j]
                        EquiMat[i,'Pr',j]<-(ParaMat[i,'r']/ParaMat[i,'d'])*EquiMat[i,'S1',j]}
        }
        return(EquiMat)                        }


par(mfrow=c(1,1))
for (i in c(1,10,100)){
        
        NumberofGene<-i
        LengthOfChain<-7
        ParaMat<-matrix(data = 1,nrow = LengthOfChain,ncol = 4)
        colnames(ParaMat)<-c('k12','k21','r','d')
        ParaMat[,'k12']<-1
        ParaMat[,'r']<-2
        ParaMat[,'d']<-1
        
        IM<-seq(0,100,length.out = 100)
        Target<-SimuChains(NOG = NumberofGene,IM = IM,LengthOfChain = LengthOfChain,k12 = ParaMat[,1],k21 =ParaMat[,2],r = ParaMat[,3],d = ParaMat[,4] )
        
        ColVec<-rainbow(n = LengthOfChain)
        
        plot(Target[1,1,]/NumberofGene~IM,type='l',col=1,lwd=2,ylab='% of Gene on',main=paste('N=',i))
        
        for (i in seq(3,LengthOfChain,by=2)){ 
                lines(Target[i,1,]/NumberofGene~IM,type='l',col=ColVec[i],lwd=2)
        }
        
        legend('topright',legend = paste('Depth=',seq(3,LengthOfChain,by=2),sep=''),lwd = 2,
               col = ColVec[seq(1,LengthOfChain,by=2)],cex=1.5)
}

par(mfrow=c(1,1))






##SYSTEMATICALL LOOK AT LONG CHAIN 
###Inhbition chain 
SimuChains<-function(NOG,IM,LengthOfChain,k12,k21,r,d){
        NumberofGene<-NOG
        LengthOfChain<-LengthOfChain
        
        
        ParaMat<-matrix(data = 1,nrow = LengthOfChain,ncol = 4)
        colnames(ParaMat)<-c('k12','k21','r','d')
        ParaMat[,'k12']<-k12
        ParaMat[,'k21']<-k21
        ParaMat[,'r']<-r
        ParaMat[,'d']<-d
        
        IM<-IM
        
        EquiMat<-array(0,dim=c(LengthOfChain,3,length(IM)))
        colnames(EquiMat)<-c('S1','S2','Pr')
        
        for (j in 1:length(IM)){
                i<-1#first node 
                EquiMat[i,'S1',j]<-NumberofGene/((ParaMat[i,'k12']/ParaMat[i,'k21'])*IM[j]+1)
                EquiMat[i,'S2',j]<-NumberofGene-EquiMat[i,'S1',j]
                EquiMat[i,'Pr',j]<-(ParaMat[i,'r']/ParaMat[i,'d'])*EquiMat[i,'S1',j]
                
                for (i in 2:nrow(EquiMat)){
                        EquiMat[i,'S1',j]<-NumberofGene/((ParaMat[i,'k12']/ParaMat[i,'k21'])*EquiMat[i-1,'Pr',j]+1)
                        EquiMat[i,'S2',j]<-NumberofGene-EquiMat[i,'S1',j]
                        EquiMat[i,'Pr',j]<-(ParaMat[i,'r']/ParaMat[i,'d'])*EquiMat[i,'S1',j]}
        }
        return(EquiMat)                        }


#get the parametes 


IM<-c(0,10000)
LengthOfChain<-10
NumberOfGenes<-c(1,10,100)
NumRep<-1000

##LHS sampling to get other parameters 

library(lhs);library(abind)
ParaSets<-rbind(c(k12=0.1,k21=0.1,r=0.1,d=0.1),
                c(k12=10,k21=10,r=10,d=10))


par(mfrow=c(1,1))



for (j in 1:length(NumberOfGenes)){
        AllSimus<-NULL #vector to sttore all the simulation results 
        
        
        for (i in 1:NumRep){
                ParaLHSVec<-randomLHS(n = LengthOfChain,k = 4)
                
                ParaSpace<-apply(ParaLHSVec,MARGIN = 1,FUN = function(x)(x*(ParaSets[2,]-ParaSets[1,])+ParaSets[1,]))#generate the parameter space
                
                
                
                SImResult<-SimuChains(NOG = NumberOfGenes[j],IM = IM,LengthOfChain = LengthOfChain,
                                      k12 = ParaSpace['k12',],k21 = ParaSpace['k21',],r = ParaSpace['r',],d = ParaSpace['d',])
                
                
                HLE<-apply(SImResult[,3,],1,max)
                LLE<-apply(SImResult[,3,],1,min)
                AE<-HLE-LLE#Absluate effectiveness
                RE<-(HLE-LLE)/((HLE+LLE)/2)#relative effectiveness 
                
                
                OutputVec<-rbind(AE,RE,HLE,LLE)
                
                
                AllSimus<-abind(AllSimus,OutputVec,along = 3)}
        
        
        
        
        MeanVec<-rowMeans(AllSimus[2,,])
        plot(MeanVec,pch=4,cex=1,ylab='RE',log='',main=paste('N=',NumberOfGenes[j]),ylim=c(1e-4,2))
        SDVec<-apply(AllSimus[2,,],MARGIN = 1,sd)
        arrows(x0=1:10,y0=MeanVec,x1=1:10,y1=MeanVec+SDVec,angle=90,lwd=2,col='orange')
        arrows(x0=1:10,y0=MeanVec,x1=1:10,y1=MeanVec-SDVec,angle=90,lwd=2,col='orange')
        
        #plot(rowMeans(AllSimus[1,,]),pch=4,cex=1,ylab='AE',log='y',main=paste('N=',NumberOfGenes[j]))
        #plot(rowMeans(AllSimus[3,,]),pch=4,cex=1,ylab='HLE',log='y',main=paste('N=',NumberOfGenes[j]))
        #plot(rowMeans(AllSimus[4,,]),pch=4,cex=1,ylab='LLE',log='y',main=paste('N=',NumberOfGenes[j]))
        
        
}
par(mfrow=c(1,1))




#dev.off()



# chain of RE

par(mfrow=c(1,1))
curve(from=0,to=3,n=100,expr=(10+1*x^7)/(1+x^7),ylim=c(0,10),lwd=2,xaxt='n',yaxt='n',xlab='',ylab='')
arrows(x0=2.0,y0=5,x1=2,y1=10,angle=90,lwd=2,col='orange')
arrows(x0=2.0,y0=5,x1=2,y1=1,angle=90,lwd=2,col='orange')

abline(h=1,lwd=1.5,lty=2,col='blue')
abline(h=10,lwd=1.5,lty=2,col='red')

curve(from=0,to=3,n=100,expr=(2+8*x^7)/(1+x^7),ylim=c(0,10),lwd=2,xaxt='n',yaxt='n',xlab='',ylab='')
arrows(x0=2.0,y0=5,x1=2,y1=8,angle=90,lwd=2,col='orange')
arrows(x0=2.0,y0=5,x1=2,y1=2,angle=90,lwd=2,col='orange')

abline(h=2,lwd=1.5,lty=2,col='blue')
abline(h=8,lwd=1.5,lty=2,col='red')

curve(from=0,to=3,n=100,expr=(7+3*x^7)/(1+x^7),ylim=c(0,10),lwd=2,xaxt='n',yaxt='n',xlab='',ylab='')
arrows(x0=2.0,y0=5,x1=2,y1=7,angle=90,lwd=2,col='orange')
arrows(x0=2.0,y0=5,x1=2,y1=3,angle=90,lwd=2,col='orange')


abline(h=3,lwd=1.5,lty=2,col='blue')
abline(h=7,lwd=1.5,lty=2,col='red')

curve(from=0,to=3,n=100,expr=(4.5+6.5*x^7)/(1+x^7),ylim=c(0,10),lwd=2,xaxt='n',yaxt='n',xlab='',ylab='')

arrows(x0=2.0,y0=5,x1=2,y1=6.5,angle=90,lwd=2,col='orange')
arrows(x0=2.0,y0=5,x1=2,y1=4.5,angle=90,lwd=2,col='orange')

abline(h=4.5,lwd=1.5,lty=2,col='blue')
abline(h=6.5,lwd=1.5,lty=2,col='red')

##N>>1


par(mfrow=c(1,4))
curve(from=0,to=3,n=100,expr=(10+1*x^7)/(1+x^7),ylim=c(0,10),lwd=2,xaxt='n',yaxt='n',xlab='',ylab='')
arrows(x0=2.0,y0=5,x1=2,y1=10,angle=90,lwd=2,col='orange')
arrows(x0=2.0,y0=5,x1=2,y1=1,angle=90,lwd=2,col='orange')

abline(h=1,lwd=1.5,lty=2,col='blue')
abline(h=10,lwd=1.5,lty=2,col='red')

curve(from=0,to=3,n=100,expr=(1.1+9.5*x^7)/(1+x^7),ylim=c(0,10),lwd=2,xaxt='n',yaxt='n',xlab='',ylab='')
arrows(x0=2.0,y0=5,x1=2,y1=9.5,angle=90,lwd=2,col='orange')
arrows(x0=2.0,y0=5,x1=2,y1=1.1,angle=90,lwd=2,col='orange')

abline(h=1.1,lwd=1.5,lty=2,col='blue')
abline(h=9.5,lwd=1.5,lty=2,col='red')

curve(from=0,to=3,n=100,expr=(9.0+1.5*x^7)/(1+x^7),ylim=c(0,10),lwd=2,xaxt='n',yaxt='n',xlab='',ylab='')
arrows(x0=2.0,y0=5,x1=2,y1=9,angle=90,lwd=2,col='orange')
arrows(x0=2.0,y0=5,x1=2,y1=1.5,angle=90,lwd=2,col='orange')


abline(h=1.5,lwd=1.5,lty=2,col='blue')
abline(h=9,lwd=1.5,lty=2,col='red')

curve(from=0,to=3,n=100,expr=(2+8.5*x^7)/(1+x^7),ylim=c(0,10),lwd=2,xaxt='n',yaxt='n',xlab='',ylab='')

arrows(x0=2.0,y0=5,x1=2,y1=8.5,angle=90,lwd=2,col='orange')
arrows(x0=2.0,y0=5,x1=2,y1=2,angle=90,lwd=2,col='orange')

abline(h=2,lwd=1.5,lty=2,col='blue')
abline(h=8.5,lwd=1.5,lty=2,col='red')
#dev.off()